# Generated by Django 5.2.11 on 2026-05-09 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
        ('stores', '0009_storepaymentmethod_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='provider_receipt_url',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='provider_transaction_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='notes',
            field=models.TextField(blank=True, help_text='Accountant notes or walk-in payment details', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.ForeignKey(blank=True, help_text='Which offline payment method the customer used', null=True, on_delete=django.db.models.deletion.SET_NULL, to='stores.storepaymentmethod'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('WAIVED', 'Waived'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20),
        ),
    ]
