# Generated by Django 5.2.11 on 2026-05-24 22:56

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_remove_payment_provider_receipt_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], db_index=True, default='PENDING', max_length=20),
        ),
    ]
