# Generated by Django 5.2.11 on 2026-03-08 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_loyalty_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('SELLER', 'Seller'), ('ADMIN', 'Admin'), ('CHEF', 'Chef'), ('DELIVERY', 'Delivery Driver'), ('ACCOUNTANT', 'Accountant')], default='CUSTOMER', max_length=20),
        ),
    ]
