# Generated by Django 5.1.2 on 2026-05-22 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accepted_liability_policy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='policy_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
