# Generated by Django 5.1.2 on 2026-05-23 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_accepted_liability_policy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('SELLER', 'Seller'), ('ADMIN', 'Admin'), ('SUPERUSER', 'Superuser'), ('CHEF', 'Chef'), ('DELIVERY', 'Delivery Driver'), ('ACCOUNTANT', 'Accountant')], default='CUSTOMER', max_length=20),
        ),
    ]
