# Generated by Django 5.2.11 on 2026-06-06 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_pushdevice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('SELLER', 'Seller'), ('ADMIN', 'Admin'), ('SUPERUSER', 'Superuser'), ('CHAPUUSTAFF', 'Chapuu Staff'), ('CHEF', 'Chef'), ('DELIVERY', 'Delivery Driver'), ('ACCOUNTANT', 'Accountant')], default='CUSTOMER', max_length=20),
        ),
    ]
