# Generated by Django 5.2.11 on 2026-06-06 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0026_alter_notice_options_notice_cleared_by'),
        ('users', '0009_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_stores',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='stores.store'),
        ),
    ]
