# Generated by Django 5.2.11 on 2026-05-24 22:56

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyinvoice',
            name='status',
            field=models.CharField(choices=[('UNPAID', 'Unpaid'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue')], db_index=True, default='UNPAID', max_length=20),
        ),
    ]
