# Generated by Django 5.2.11 on 2026-05-24 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_auto_20260524_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyinvoice',
            name='status',
            field=models.CharField(choices=[('UNPAID', 'Unpaid'), ('PENDING_REVIEW', 'Pending Review'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue')], default='UNPAID', max_length=20),
        ),
    ]
