# Generated by Django 5.2.11 on 2026-06-06 11:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_alter_monthlyinvoice_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commissionledgerentry',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='commissionledgerentry',
            name='entry_type',
            field=models.CharField(choices=[('COMMISSION', 'Fulfillment Commission'), ('CANCELLATION_FEE', 'Scheduled Cancellation Platform Share')], default='COMMISSION', max_length=30),
        ),
    ]
