server {
  listen 80;
  
  location /media/ {
    alias /usr/share/nginx/html/media/;
    add_header Cache-Control "public, max-age=86400";
    add_header X-Content-Type-Options nosniff;
  }
  
  location /static/ {
    alias /usr/share/nginx/html/static/;
    add_header Cache-Control "public, max-age=31536000, immutable";
  }
}
