http:
  routers:
    backend:
      rule: "PathPrefix(`/api`) || PathPrefix(`/admin`) || PathPrefix(`/static`) || PathPrefix(`/media`) || PathPrefix(`/ws`)"
      service: backend
      entryPoints:
        - web
      middlewares:
        - proxy-headers

    frontend:
      rule: "PathPrefix(`/`)"
      service: frontend
      entryPoints:
        - web
      priority: 1

  services:
    backend:
      loadBalancer:
        servers:
          - url: "http://backend:8000"
    frontend:
      loadBalancer:
        servers:
          - url: "http://frontend:80"

  middlewares:
    proxy-headers:
      headers:
        customRequestHeaders:
          X-Forwarded-Proto: "http"
          X-Forwarded-Host: "13.127.242.204"
