# Generated by Django 5.2.11 on 2026-03-07 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_fulfillment_mode'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storereview',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review', to='orders.order'),
        ),
    ]
