# Generated by Django 5.2.11 on 2026-05-07 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_ingredient_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddConstraint(
            model_name='inventorystock',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('ingredient__isnull', True), ('product__isnull', False)), models.Q(('ingredient__isnull', False), ('product__isnull', True)), _connector='OR'), name='stock_must_belong_to_product_or_ingredient'),
        ),
    ]
