# Generated by Django 5.2.11 on 2026-05-24 22:56

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_category_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, db_index=True),
        ),
    ]
