# Generated by Django 5.2.11 on 2026-05-24 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_product_is_active'),
        ('stores', '0022_alter_store_is_active_alter_store_is_open'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['store', 'is_active'], name='product_store_active_idx'),
        ),
    ]
