# Generated by Django 5.2.11 on 2026-03-03 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_store_contact_email_store_contact_phone_store_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='base_delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('media', models.FileField(help_text='Image or Video for the TV dashboard', upload_to='ads/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(blank=True, help_text='Null means global admin ad.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='stores.store')),
            ],
        ),
    ]
