# Generated by Django 5.2.11 on 2026-03-04 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_store_base_delivery_fee_advertisement'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='e.g. TZS, USD, KES', max_length=10, unique=True)),
                ('name', models.CharField(help_text='e.g. Tanzanian Shilling', max_length=50)),
                ('symbol', models.CharField(help_text='e.g. TSh, $, KSh', max_length=10)),
                ('rate_to_base', models.DecimalField(decimal_places=6, default=1.0, help_text='How many units of the base currency (TZS) equal 1 unit of this currency. TZS=1.0, USD≈2500.', max_digits=14)),
                ('is_default', models.BooleanField(default=False, help_text='The primary display currency.')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Currency Configs',
            },
        ),
    ]
