# Generated by Django 5.2.11 on 2026-03-04 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_currencyconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='store_type',
            field=models.CharField(choices=[('RESTAURANT', 'Restaurant'), ('SHOP', 'Shop')], default='RESTAURANT', max_length=20),
        ),
    ]
