# Generated by Django 5.2.11 on 2026-03-08 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_store_store_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notices_sent', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(blank=True, help_text="If null, it's a global notice.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='stores.store')),
                ('target_user', models.ForeignKey(blank=True, help_text='If null, goes to all staff in the store/global.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notices_received', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
