# Generated by Django 5.2.11 on 2026-05-07 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0007_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='is_open',
            field=models.BooleanField(default=True, help_text='Store open/closed status toggle.'),
        ),
        migrations.CreateModel(
            name='StorePaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(help_text='e.g. M-Pesa, Bank Transfer, Cash', max_length=100)),
                ('account_name', models.CharField(blank=True, max_length=255, null=True)),
                ('account_number', models.CharField(blank=True, max_length=100, null=True)),
                ('instructions', models.TextField(blank=True, help_text='e.g. Send to Till Number 123456', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='stores.store')),
            ],
        ),
    ]
