# Generated by Django 5.2.11 on 2026-05-07 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0008_store_is_open_storepaymentmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='storepaymentmethod',
            name='image',
            field=models.ImageField(blank=True, help_text='Network logo/image', null=True, upload_to='payment_methods/'),
        ),
    ]
