# Generated by Django 5.2.11 on 2026-05-21 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0010_add_read_by_to_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchensettings',
            name='default_prep_time_minutes',
            field=models.PositiveIntegerField(default=30, help_text='Fallback prep time in minutes if product estimated_prep_time_minutes is not set'),
        ),
    ]
