# Generated by Django 5.2.11 on 2026-05-22 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0011_kitchensettings_default_prep_time_minutes'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSupportConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('support_phone', models.CharField(default='+255 700 000 000', help_text='Support telephone number (tel:)', max_length=50)),
                ('support_email', models.EmailField(default='support@chapuu.co.tz', help_text='Support email address (mailto:)', max_length=254)),
                ('support_sms', models.CharField(default='+255 700 000 000', help_text='Support SMS number (sms:)', max_length=50)),
                ('support_whatsapp', models.CharField(default='255700000000', help_text="WhatsApp number (without '+' or leading zeros) or link", max_length=100)),
                ('policy_warning', models.TextField(default="Violation of the system's policy (such as consecutive delivery locking or fraud) can get your store taken down permanently.", help_text='Policy warning shown to sellers for violations.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Support Config',
                'verbose_name_plural': 'System Support Configs',
            },
        ),
    ]
