# Generated by Django 5.2.11 on 2026-05-22 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0012_systemsupportconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='store_galleries/')),
                ('caption', models.CharField(blank=True, help_text='Short description of the photo', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='stores.store')),
            ],
        ),
    ]
