# Generated by Django 5.1.2 on 2026-05-22 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0013_storegalleryimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalPaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. M-Pesa, Cash, Bank Transfer', max_length=100, unique=True)),
                ('logo', models.ImageField(blank=True, help_text='Official provider logo', null=True, upload_to='global_payment_methods/')),
                ('requires_account_details', models.BooleanField(default=True, help_text='If True, sellers must provide Account Name and Number')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='storepaymentmethod',
            name='global_payment_method',
            field=models.ForeignKey(blank=True, help_text='Underlying global payment option template', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='store_methods', to='stores.globalpaymentmethod'),
        ),
    ]
