# Generated by Django 5.2.11 on 2026-05-23 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0014_globalpaymentmethod_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsupportconfig',
            name='seller_support_email',
            field=models.EmailField(default='vendor-support@chapuu.co.tz', help_text='Dedicated Seller Support Email', max_length=254),
        ),
        migrations.AddField(
            model_name='systemsupportconfig',
            name='seller_support_phone',
            field=models.CharField(default='+255 700 000 111', help_text='Dedicated Seller Support Telephone', max_length=50),
        ),
        migrations.AddField(
            model_name='systemsupportconfig',
            name='seller_support_sms',
            field=models.CharField(default='+255 700 000 111', help_text='Dedicated Seller Support SMS', max_length=50),
        ),
    ]
