# Generated by Django 5.2.11 on 2026-05-24 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0015_systemsupportconfig_seller_support_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Auto-set via Get Location button', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Auto-set via Get Location button', max_digits=9, null=True),
        ),
    ]
