# Generated by Django 5.2.11 on 2026-05-24 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0016_store_latitude_store_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='directions',
            field=models.TextField(blank=True, help_text='Local landmark details or delivery directions provided by the seller', null=True),
        ),
    ]
