# Generated by Django 5.2.11 on 2026-05-24 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0017_store_directions'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='requires_table_for_dine_in',
            field=models.BooleanField(default=True, help_text='If True, table selection is mandatory for dine-in orders.'),
        ),
    ]
