# Generated by Django 5.2.11 on 2026-05-24 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0018_store_requires_table_for_dine_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='free_trial_end',
            field=models.DateTimeField(blank=True, help_text='End date-time of promotional free trial', null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='free_trial_start',
            field=models.DateTimeField(blank=True, help_text='Start date-time of promotional free trial', null=True),
        ),
    ]
