# Generated by Django 5.2.11 on 2026-05-24 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0019_store_free_trial_end_store_free_trial_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='working_hours',
            field=models.CharField(default='08:00 AM - 10:00 PM', help_text='e.g. 08:00 AM - 10:00 PM', max_length=255),
        ),
    ]
