# Generated by Django 5.2.11 on 2026-05-24 22:56

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0020_store_working_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='is_active',
            field=models.BooleanField(default=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='is_open',
            field=models.BooleanField(default=True, db_index=True),
        ),
    ]
