# Generated by Django 5.2.11 on 2026-05-24 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0021_auto_20260524_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='is_open',
            field=models.BooleanField(default=True, help_text='Store open/closed status toggle.'),
        ),
    ]
