# Generated by Django 5.2.11 on 2026-06-06 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0023_sellerapplication_applicationdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerapplication',
            name='estimated_customer_base',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='sellerapplication',
            name='service_quality_rating',
            field=models.CharField(choices=[('LOW', 'Low'), ('MID', 'Mid'), ('HIGH', 'High'), ('SUPER', 'Super'), ('PERFECT', 'Perfect')], default='MID', max_length=10),
        ),
        migrations.AddField(
            model_name='sellerapplication',
            name='staff_notes',
            field=models.TextField(blank=True, default='', help_text='Additional explanation and notes from staff.'),
        ),
    ]
