# Generated by Django 5.2.11 on 2026-06-06 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0024_sellerapplication_estimated_customer_base_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerapplication',
            name='trial_period_days',
            field=models.IntegerField(default=0, help_text='Number of free trial days (0 means no trial)'),
        ),
    ]
