# Generated by Django 5.2.11 on 2026-06-06 10:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0025_sellerapplication_trial_period_days'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notice',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='notice',
            name='cleared_by',
            field=models.ManyToManyField(blank=True, related_name='cleared_notices', to=settings.AUTH_USER_MODEL),
        ),
    ]
