# Generated by Django 5.2.11 on 2026-03-03 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_customer_phone_order_delivery_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_message',
            field=models.TextField(blank=True, help_text="User's text transaction slip or confirmation ID.", null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_receipt',
            field=models.ImageField(blank=True, help_text="User's uploaded receipt image.", null=True, upload_to='receipts/'),
        ),
    ]
