# Generated by Django 5.2.11 on 2026-03-04 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_payment_message_order_payment_receipt'),
        ('reservations', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='reservation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_order', to='reservations.reservation'),
        ),
    ]
