# Generated by Django 5.2.11 on 2026-03-04 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='fulfillment_mode',
            field=models.CharField(choices=[('TAKEAWAY', 'Takeaway'), ('DELIVERY', 'Delivery'), ('DINE_IN', 'Dine-In'), ('RESERVATION', 'Reservation'), ('PICKUP', 'Pickup')], max_length=20),
        ),
    ]
