# Generated by Django 5.2.11 on 2026-03-08 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_fulfillment_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Delivery or pickup fee set by seller/accountant.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('CREATED', 'Created'), ('AWAITING_PAYMENT', 'Awaiting Payment'), ('PAID', 'Paid'), ('QUEUED', 'Queued'), ('PREPARING', 'Preparing'), ('READY', 'Ready'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired'), ('REFUNDED', 'Refunded')], default='CREATED', max_length=20),
        ),
    ]
