# Generated by Django 5.2.11 on 2026-05-09 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_delivery_fee_alter_order_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_instant_payment',
            field=models.BooleanField(default=False, help_text='True when a walk-in customer pays in person at time of order. Skips AWAITING_PAYMENT state and goes directly to PAID. Can only be set by store staff (SELLER, ADMIN, ACCOUNTANT, CHEF). Must NOT be used with DELIVERY fulfillment mode.'),
        ),
    ]
