# Generated by Django 5.2.11 on 2026-05-21 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_ordereventlog_performed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_code',
            field=models.CharField(blank=True, help_text='6-digit verification code', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_code_attempts',
            field=models.PositiveIntegerField(default=0, help_text='Verification attempts count'),
        ),
        migrations.AddField(
            model_name='order',
            name='prep_time_option',
            field=models.CharField(choices=[('DYNAMIC', 'Dynamic (System-Calculated)'), ('CUSTOM', 'Custom Start Time')], default='DYNAMIC', max_length=15),
        ),
        migrations.AddField(
            model_name='order',
            name='reschedule_requested_start_time',
            field=models.DateTimeField(blank=True, help_text='Requested prep start time', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='reschedule_requested_time',
            field=models.DateTimeField(blank=True, help_text='Requested scheduled_time', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='reschedule_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='scheduled_start_time',
            field=models.DateTimeField(blank=True, help_text='When prep should begin', null=True),
        ),
    ]
