# Generated by Django 5.2.11 on 2026-05-22 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_delivery_code_order_delivery_code_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='Locked due to exceeding maximum verification attempts.'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_suspicious',
            field=models.BooleanField(default=False, help_text='Flagged as suspicious due to failed verification attempts.'),
        ),
    ]
