# Generated by Django 5.2.11 on 2026-05-23 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_is_locked_order_is_suspicious'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='reschedule_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times this order has been successfully rescheduled'),
        ),
        migrations.AddField(
            model_name='order',
            name='reschedule_rejection_reason',
            field=models.TextField(blank=True, help_text='Reason why the reschedule request was rejected', null=True),
        ),
    ]
