# Generated by Django 5.2.11 on 2026-05-23 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_order_reschedule_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='reschedule_request_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of reschedule requests submitted by the customer'),
        ),
        migrations.CreateModel(
            name='OrderRescheduleRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_time', models.DateTimeField(help_text='Requested scheduled_time')),
                ('requested_start_time', models.DateTimeField(help_text='Requested prep start time')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reschedule_requests', to='orders.order')),
            ],
        ),
    ]
