# Generated by Django 5.2.11 on 2026-05-24 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_order_reschedule_request_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_directions',
            field=models.TextField(blank=True, help_text='Specific landmarks or detailed directions for delivery rider', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text="Customer's GPS latitude captured at checkout", max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text="Customer's GPS longitude captured at checkout", max_digits=9, null=True),
        ),
    ]
