# Generated by Django 5.2.11 on 2026-05-24 23:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_alter_order_created_at_alter_order_state'),
        ('reservations', '0002_initial'),
        ('stores', '0022_alter_store_is_active_alter_store_is_open'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('CREATED', 'Created'), ('AWAITING_PAYMENT', 'Awaiting Payment'), ('PAID', 'Paid'), ('QUEUED', 'Queued'), ('PREPARING', 'Preparing'), ('READY', 'Ready'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired'), ('REFUNDED', 'Refunded')], db_index=True, default='CREATED', max_length=20),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['store', 'state'], name='order_store_state_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['store', 'created_at'], name='order_store_created_idx'),
        ),
    ]
