# Generated by Django 5.2.11 on 2026-05-25 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_add_performance_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_fee_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('AGREED', 'Agreed'), ('RENEGOTIATE', 'Renegotiate')], default='PENDING', help_text='Fulfillment delivery fee negotiation status', max_length=20),
        ),
    ]
