# Generated by Django 5.2.11 on 2026-06-06 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_order_delivery_fee_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Amount discounted at POS', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='pos_custom_items',
            field=models.JSONField(blank=True, help_text='JSON list of non-catalog custom items added at POS', null=True),
        ),
    ]
